# Keep a Changelog labels
# https://keepachangelog.com/en/1.0.0/
- color: 0e8a16
  description: "For new features"
  name: "changelog: Added"
- color: af99e5
  description: "For changes in existing functionality"
  name: "changelog: Changed"
- color: FFA500
  description: "For soon-to-be removed features"
  name: "changelog: Deprecated"
- color: 00A800
  description: "For any bug fixes"
  name: "changelog: Fixed"
- color: ff0000
  description: "For now removed features"
  name: "changelog: Removed"
- color: 045aa0
  description: "In case of vulnerabilities"
  name: "changelog: Security"
- color: fbca04
  description: "Exclude PR from release draft"
  name: "changelog: skip"

# Other labels
- color: 0366d6
  description: "For dependencies"
  name: dependencies
- color: f4660e
  description: ""
  name: Hacktoberfest
- color: f4660e
  description: "To credit accepted Hacktoberfest PRs"
  name: hacktoberfest-accepted
- color: d65e88
  description: "Deploy and release"
  name: release
- color: fbca04
  description: "Unit tests, linting, CI, etc."
  name: testing
